### ISSUE TITLE
Production build is really slow.

### ISSUE THREAD

**Issue by zicsus** [MobileFirstLLC/extension-cli#51] opened 2021-04-15 12:55 UTC
**Describe the bug**
Production build of scripts is really slow without any significant reason. 

**To Reproduce**
`npm run build`

**Expected behavior**
I think than production build should go faster than current speed. There is not generation of source map or anything just same compilation as development with some minification. is the minifaction the issue? 
When I just used webpack for compiling, the speeds were significantly faster than current time even when source maps where generated with minifcation.

**Comment by zicsus** [comment] 2021-04-16 04:12
@nkrusch any ideas?

**Comment by nkrusch** [comment] 2021-04-16 04:23
@zicsus are you using the latest alpha?

**Comment by zicsus** [comment] 2021-04-16 04:44
I'm not sure if this problem is recent or old because I noticed when I started compiling large projects. I will take look at latest alpha and let you know.

**Comment by nkrusch** [comment] 2021-04-16 04:45
I have two thoughts which I have been thinking about to address this type of issues:

1. Create integration (or system?) tests to test against different configurations to make it easier to identify issues. I mean having various sample project w/ configs and using it to drive the CLI and then check that output is what was expected. 

2. secondly benchmark those tests and develop some data around how long it takes to run different configurations and detect degradation, if it happens.

I'm thinking running on tags using CI.

**Comment by zicsus** [comment] 2021-04-16 04:52
It persists in latest alpha `1.0.3-alpha.1`. I'm also getting warning like this- 
![Capture](https://user-images.githubusercontent.com/31795543/114973010-30295000-9e9d-11eb-81f6-17a484848d24.PNG)

The weird part is that development build does not have this warning. Something related to production is causing this. 
We also need to take a look at development builds because they are slower than normal webpack setups.

**Comment by nkrusch** [comment] 2021-04-16 07:04
Try viewing what is being included in `capture.js` `6e4035c6674b924a9ff0.js` after it builds vs. what _should_ be in included per configs. It seems like it is slow and showing this warning because the generated file is so large.

**Comment by zicsus** [comment] 2021-04-16 13:54
@nkrusch `capture.js` includes some third party (3 packages to be precise) includes but nothing out of ordinary. Even if I remove `capture.js`, it is still slow build time.

**Comment by nkrusch** [comment] 2021-04-16 19:27
next options: 

- is it specifically building javascript that is slow, or some other build step(s)? It runs steps sequentially and you can observe the delays of each step in the output.  Also compare between dev build to compare differences in timing to say which step(s) in the build are slow.

- backtrack the CLI version to see at which point it becomes slow to identify when the change occurred

- (there are many dependencies) if you identify the lag is with building scripts specifically, I would also check if using different versions of `webpack-stream` makes any difference.

**Comment by nkrusch** [comment] 2021-04-17 18:54
I don't know if you have had a chance to test this further? I am now wondering how much this impacts the build time especially since it sounds like the issues is with prod and not dev:

```
const webpackOptions = { mode: isProd ? "production" : "development" };
```

It is the only difference between the two.

**Comment by zicsus** [comment] 2021-04-17 21:04
I haven't tested it yet. Webpack might be doing some extra optimations in production mode but its there suggested way. I wonder why it's making so much difference.

**Comment by zicsus** [comment] 2021-04-26 06:01
According to this page- https://webpack.js.org/configuration/mode/ changing mode to production brings some additional optimizations.

**Comment by nkrusch** [comment] 2021-04-26 06:07
I was assuming that. If you try building locally, either specifying no mode or dev mode, does that makes any difference in the build time? Trying to figure out the cause of the latency. If it makes no difference then the cause is somewhere else.

**Comment by zicsus** [comment] 2021-04-26 06:30
Just tested it and setting mode to development (permanently) and making `devtool: none` gives really fast build times in production. I will keep `devtool: cheap-source-map`  for development. 
Creating a PR in some time.

**Comment by zicsus** [comment] 2021-04-26 06:34
Here you go- https://github.com/MobileFirstLLC/extension-cli/pull/54

**Comment by nkrusch** [comment] 2021-04-27 00:43
First, great that this explains the cause!

webpack dev mode does not minifying the source. I believe it concatenates the files. It would explains why 3rd party files build fast. 

The flip-side is it does not minify js files in cases where that \*is\* the desired behavior.

How about best of both words and make the mode configurable?

I'm thinking:

```
  {
    "name": "content_script",
    "src": "./src/*.js",
    "mode": "development"
  }
```      

when the use case is to always use specific mode. If not specified default to `--env` flag.

**Comment by nkrusch** [comment] 2021-04-27 00:58
How does this look to you?

https://github.com/MobileFirstLLC/extension-cli/pull/55/files

**Comment by zicsus** [comment] 2021-04-27 04:32
You're good to go. Ignore my comment on the PR. After thinking for a while I think that it can be really useful.

**Comment by nkrusch** [comment] 2021-04-27 05:38
Let me know if the latest alpha resolves this issue? If yes, I will roll out a patch and we can close this.

**Comment by zicsus** [comment] 2021-04-27 06:16
Yup! you can proceed.

**Closed** 2021-04-27 07:05 UTC
